# Generated by Django 3.1.3 on 2020-11-26 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FyDataSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('period', models.IntegerField()),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_duns_no', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=150)),
                ('e_name', models.CharField(max_length=150)),
                ('e_email', models.CharField(max_length=100)),
                ('e_jd', models.CharField(max_length=50)),
                ('refined_jd', models.CharField(max_length=10)),
                ('e_posting_profit_center', models.CharField(max_length=100)),
                ('e_Posting_profit_center_d', models.CharField(max_length=100)),
                ('e_profit_center_ba', models.CharField(max_length=100)),
                ('e_profit_center_bl', models.CharField(max_length=100)),
                ('profit_center_usi_ind', models.CharField(max_length=100)),
                ('wbs_l1', models.CharField(max_length=100)),
                ('wbs_l1_text', models.CharField(max_length=100)),
                ('wbs_l2', models.CharField(max_length=100)),
                ('wbs_l2_text', models.CharField(max_length=100)),
                ('wbs_business_model_mix', models.CharField(max_length=100)),
                ('mo_solution', models.CharField(max_length=100)),
                ('mo_sub_solution', models.CharField(max_length=100)),
                ('csh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fte', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fydatasummary')),
            ],
        ),
    ]
