# Generated by Django 3.1.3 on 2020-11-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fydatasummary',
            name='no_of_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fydatasummary',
            name='total_fte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
