# Generated by Django 3.1.3 on 2020-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201126_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fydatasummary',
            name='total_fte',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
