# Generated by Django 3.1.3 on 2020-11-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201126_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fydata',
            old_name='e_Posting_profit_center_d',
            new_name='e_posting_profit_center_d',
        ),
    ]
